use super::TrapGroup;

#[derive(Clone, Copy, Debug)]
pub struct TrapMeta {
    pub code: u16,
    pub group: TrapGroup,
    pub name: &'static str,
}

pub fn lookup(code: u16) -> TrapMeta {
    let (group, name) = match code {
        0xA01E => (TrapGroup::Mem, "sysTrapMemHandleNew"),
        0xA012 => (TrapGroup::Mem, "sysTrapMemChunkFree"),
        0xA021 => (TrapGroup::Mem, "sysTrapMemHandleLock"),
        0xA022 => (TrapGroup::Mem, "sysTrapMemHandleUnlock"),
        0xA026 => (TrapGroup::Mem, "sysTrapMemMove"),
        0xA027 => (TrapGroup::Mem, "sysTrapMemSet"),
        0xA02D => (TrapGroup::Mem, "sysTrapMemHandleSize"),
        0xA035 => (TrapGroup::Mem, "sysTrapMemPtrUnlock"),
        0xA02B => (TrapGroup::Mem, "sysTrapMemHandleFree"),
        0xA041 => (TrapGroup::Dm, "sysTrapDmCreateDatabase"),
        0xA045 => (TrapGroup::Dm, "sysTrapDmFindDatabase"),
        0xA046 => (TrapGroup::Dm, "sysTrapDmDatabaseInfo"),
        0xA047 => (TrapGroup::Dm, "sysTrapDmSetDatabaseInfo"),
        0xA049 => (TrapGroup::Dm, "sysTrapDmOpenDatabase"),
        0xA04A => (TrapGroup::Dm, "sysTrapDmCloseDatabase"),
        0xA04C => (TrapGroup::Dm, "sysTrapDmOpenDatabaseInfo"),
        0xA04E => (TrapGroup::Dm, "sysTrapDmGetLastErr"),
        0xA04F => (TrapGroup::Dm, "sysTrapDmNumRecords"),
        0xA050 => (TrapGroup::Dm, "sysTrapDmRecordInfo"),
        0xA055 => (TrapGroup::Dm, "sysTrapDmNewRecord"),
        0xA05B => (TrapGroup::Dm, "sysTrapDmQueryRecord"),
        0xA05C => (TrapGroup::Dm, "sysTrapDmGetRecord"),
        0xA05D => (TrapGroup::Dm, "sysTrapDmResizeRecord"),
        0xA05E => (TrapGroup::Dm, "sysTrapDmReleaseRecord"),
        0xA05F => (TrapGroup::Dm, "sysTrapDmGetResource"),
        0xA060 => (TrapGroup::Dm, "sysTrapDmGet1Resource"),
        0xA061 => (TrapGroup::Dm, "sysTrapDmReleaseResource"),
        0xA075 => (TrapGroup::Dm, "sysTrapDmOpenDatabaseByTypeCreator"),
        0xA076 => (TrapGroup::Dm, "sysTrapDmWrite"),
        0xA07E => (TrapGroup::Dm, "sysTrapDmSet"),
        0xA08F => (TrapGroup::Sys, "sysTrapSysAppStartup"),
        0xA090 => (TrapGroup::Sys, "sysTrapSysAppExit"),
        0xA084 => (TrapGroup::Sys, "sysTrapErrDisplayFileLineMsg"),
        0xA0A9 => (TrapGroup::Sys, "sysTrapSysHandleEvent"),
        0xA0BA => (TrapGroup::Sys, "sysTrapSysLibFind"),
        0xA2AC => (TrapGroup::Sys, "sysTrapSysLibLoad"),
        0xA0C2 => (TrapGroup::Sys, "sysTrapSysRandom"),
        0xA0C5 => (TrapGroup::Str, "sysTrapStrCopy"),
        0xA0C6 => (TrapGroup::Str, "sysTrapStrCat"),
        0xA0C7 => (TrapGroup::Str, "sysTrapStrLen"),
        0xA0C8 => (TrapGroup::Str, "sysTrapStrCompare"),
        0xA0CA => (TrapGroup::Str, "sysTrapStrCaselessCompare"),
        0xA10F => (TrapGroup::Ctl, "sysTrapCtlHideControl"),
        0xA0F5 => (TrapGroup::Tim, "sysTrapTimGetSeconds"),
        0xA0F7 => (TrapGroup::Tim, "sysTrapTimGetTicks"),
        0xA0FC => (TrapGroup::Tim, "sysTrapTimSecondsToDateTime"),
        0xA11B => (TrapGroup::Evt, "sysTrapEvtAddEventToQueue"),
        0xA11D => (TrapGroup::Evt, "sysTrapEvtGetEvent"),
        0xA135 => (TrapGroup::Fld, "sysTrapFldDrawField"),
        0xA139 => (TrapGroup::Fld, "sysTrapFldGetTextPtr"),
        0xA13A => (TrapGroup::Fld, "sysTrapFldGetSelection"),
        0xA13B => (TrapGroup::Fld, "sysTrapFldHandleEvent"),
        0xA142 => (TrapGroup::Fld, "sysTrapFldSetSelection"),
        0xA14B => (TrapGroup::Fld, "sysTrapFldGetTextLength"),
        0xA153 => (TrapGroup::Fld, "sysTrapFldGetTextHandle"),
        0xA158 => (TrapGroup::Fld, "sysTrapFldSetTextHandle"),
        0xA15D => (TrapGroup::Fld, "sysTrapFldInsert"),
        0xA15E => (TrapGroup::Fld, "sysTrapFldDelete"),
        0xA163 => (TrapGroup::Fnt, "sysTrapFntGetFont"),
        0xA164 => (TrapGroup::Fnt, "sysTrapFntSetFont"),
        0xA167 => (TrapGroup::Fnt, "sysTrapFntCharHeight"),
        0xA16B => (TrapGroup::Fnt, "sysTrapFntCharsWidth"),
        0xA16D => (TrapGroup::Fnt, "sysTrapFntCharsInWidth"),
        0xA16F => (TrapGroup::Frm, "sysTrapFrmInitForm"),
        0xA171 => (TrapGroup::Frm, "sysTrapFrmDrawForm"),
        0xA173 => (TrapGroup::Frm, "sysTrapFrmGetActiveForm"),
        0xA174 => (TrapGroup::Frm, "sysTrapFrmSetActiveForm"),
        0xA178 => (TrapGroup::Frm, "sysTrapFrmGetFocus"),
        0xA179 => (TrapGroup::Frm, "sysTrapFrmSetFocus"),
        0xA17C => (TrapGroup::Frm, "sysTrapFrmGetWindowHandle"),
        0xA17E => (TrapGroup::Frm, "sysTrapFrmGetFormPtr"),
        0xA17F => (TrapGroup::Frm, "sysTrapFrmGetNumberOfObjects"),
        0xA180 => (TrapGroup::Frm, "sysTrapFrmGetObjectIndex"),
        0xA183 => (TrapGroup::Frm, "sysTrapFrmGetObjectPtr"),
        0xA18B => (TrapGroup::Frm, "sysTrapFrmSetControlGroupSelection"),
        0xA18C => (TrapGroup::Frm, "sysTrapFrmGetControlGroupSelection"),
        0xA192 => (TrapGroup::Frm, "sysTrapFrmAlert"),
        0xA194 => (TrapGroup::Frm, "sysTrapFrmCustomAlert"),
        0xA195 => (TrapGroup::Frm, "sysTrapFrmHelp"),
        0xA199 => (TrapGroup::Frm, "sysTrapFrmGetObjectBounds"),
        0xA19B => (TrapGroup::Frm, "sysTrapFrmGotoForm"),
        0xA19C => (TrapGroup::Frm, "sysTrapFrmPopupForm"),
        0xA19E => (TrapGroup::Frm, "sysTrapFrmReturnToForm"),
        0xA19F => (TrapGroup::Frm, "sysTrapFrmSetEventHandler"),
        0xA1A0 => (TrapGroup::Frm, "sysTrapFrmDispatchEvent"),
        0xA1A1 => (TrapGroup::Frm, "sysTrapFrmCloseAllForms"),
        0xA1A2 => (TrapGroup::Frm, "sysTrapFrmSaveAllForms"),
        0xA1B0 => (TrapGroup::Lst, "sysTrapLstSetDrawFunction"),
        0xA1B1 => (TrapGroup::Lst, "sysTrapLstDrawList"),
        0xA1B2 => (TrapGroup::Lst, "sysTrapLstEraseList"),
        0xA1B6 => (TrapGroup::Lst, "sysTrapLstSetHeight"),
        0xA1B7 => (TrapGroup::Lst, "sysTrapLstSetSelection"),
        0xA1B8 => (TrapGroup::Lst, "sysTrapLstSetListChoices"),
        0xA1B9 => (TrapGroup::Lst, "sysTrapLstMakeItemVisible"),
        0xA1BF => (TrapGroup::Menu, "sysTrapMenuHandleEvent"),
        0xA1D3 => (TrapGroup::Tbl, "sysTrapTblSetRowUsable"),
        0xA1EA => (TrapGroup::Tbl, "sysTrapTblSetColumnUsable"),
        0xA1C8 => (TrapGroup::Unknown, "sysTrapRctPtInRectangle"),
        0xA1CA => (TrapGroup::Tbl, "sysTrapTblDrawTable"),
        0xA1CC => (TrapGroup::Tbl, "sysTrapTblHandleEvent"),
        0xA1CE => (TrapGroup::Tbl, "sysTrapTblSelectItem"),
        0xA1CF => (TrapGroup::Tbl, "sysTrapTblGetItemInt"),
        0xA1D0 => (TrapGroup::Tbl, "sysTrapTblSetItemInt"),
        0xA1D1 => (TrapGroup::Tbl, "sysTrapTblSetItemStyle"),
        0xA1D5 => (TrapGroup::Tbl, "sysTrapTblSetCustomDrawProcedure"),
        0xA1D6 => (TrapGroup::Tbl, "sysTrapTblSetRowSelectable"),
        0xA1D8 => (TrapGroup::Tbl, "sysTrapTblSetLoadDataProcedure"),
        0xA1D9 => (TrapGroup::Tbl, "sysTrapTblSetSaveDataProcedure"),
        0xA1DB => (TrapGroup::Tbl, "sysTrapTblSetRowHeight"),
        0xA1DC => (TrapGroup::Tbl, "sysTrapTblGetColumnWidth"),
        0xA1DD => (TrapGroup::Tbl, "sysTrapTblGetRowID"),
        0xA1DE => (TrapGroup::Tbl, "sysTrapTblSetRowID"),
        0xA1E1 => (TrapGroup::Tbl, "sysTrapTblGetSelection"),
        0xA1E9 => (TrapGroup::Tbl, "sysTrapTblGetCurrentField"),
        0xA1F5 => (TrapGroup::Tbl, "sysTrapTblSetColumnSpacing"),
        0xA1EB => (TrapGroup::Tbl, "sysTrapTblGetRowHeight"),
        0xA1EC => (TrapGroup::Tbl, "sysTrapTblSetColumnWidth"),
        0xA1EE => (TrapGroup::Tbl, "sysTrapTblSetItemPtr"),
        0xA1F0 => (TrapGroup::Tbl, "sysTrapTblGetLastUsableRow"),
        0xA1F1 => (TrapGroup::Tbl, "sysTrapTblGetColumnSpacing"),
        0xA1F3 => (TrapGroup::Tbl, "sysTrapTblGetRowData"),
        0xA1F4 => (TrapGroup::Tbl, "sysTrapTblSetRowData"),
        0xA31F => (TrapGroup::Tbl, "sysTrapTblSetItemFont"),
        0xA3AA => (TrapGroup::Tbl, "sysTrapTblGetItemPtr"),
        0xA451 => (TrapGroup::Tbl, "sysTrapTblGetNumberOfColumns"),
        0xA453 => (TrapGroup::Tbl, "sysTrapTblSetSelection"),
        0xA200 => (TrapGroup::Win, "sysTrapWinGetDisplayWindow"),
        0xA213 => (TrapGroup::Win, "sysTrapWinDrawChars"),
        0xA219 => (TrapGroup::Win, "sysTrapWinGetClip"),
        0xA220 => (TrapGroup::Win, "sysTrapWinSaveBits"),
        0xA22C => (TrapGroup::Sys, "sysTrapPrefGetPreferences"),
        0xA226 => (TrapGroup::Win, "sysTrapWinDrawBitmap"),
        0xA456 => (TrapGroup::Win, "sysTrapWinGetBounds"),
        0xA470 => (TrapGroup::Sys, "sysTrapPinsDispatch"),
        0xA234 => (TrapGroup::Snd, "sysTrapSndPlaySystemSound"),
        0xA27B => (TrapGroup::Sys, "sysTrapFtrGet"),
        0xA27C => (TrapGroup::Sys, "sysTrapFtrSet"),
        0xA25F => (TrapGroup::Sys, "sysTrapDayOfWeek"),
        0xA266 => (TrapGroup::Sys, "sysTrapDateToAscii"),
        0xA267 => (TrapGroup::Sys, "sysTrapDateToDOWDMFormat"),
        0xA268 => (TrapGroup::Sys, "sysTrapTimeToAscii"),
        0xA2E9 => (TrapGroup::Sys, "sysTrapSysTicksPerSecond"),
        _ if (0xA000..=0xA03F).contains(&code) => (TrapGroup::Mem, "memTrap"),
        _ if (0xA040..=0xA07F).contains(&code) => (TrapGroup::Dm, "dmTrap"),
        _ if (0xA089..=0xA0C4).contains(&code) => (TrapGroup::Sys, "sysTrap"),
        _ if (0xA0C5..=0xA0CF).contains(&code) => (TrapGroup::Str, "strTrap"),
        _ if (0xA0F5..=0xA100).contains(&code) => (TrapGroup::Tim, "timTrap"),
        _ if (0xA11A..=0xA132).contains(&code) => (TrapGroup::Evt, "evtTrap"),
        _ if (0xA10D..=0xA119).contains(&code) => (TrapGroup::Ctl, "ctlTrap"),
        _ if (0xA133..=0xA162).contains(&code) => (TrapGroup::Fld, "fldTrap"),
        _ if (0xA163..=0xA16E).contains(&code) => (TrapGroup::Fnt, "fntTrap"),
        _ if (0xA16F..=0xA1A5).contains(&code) => (TrapGroup::Frm, "frmTrap"),
        _ if (0xA1B0..=0xA1BC).contains(&code) => (TrapGroup::Lst, "lstTrap"),
        _ if (0xA1BD..=0xA1C3).contains(&code) => (TrapGroup::Menu, "menuTrap"),
        _ if (0xA1C6..=0xA1ED).contains(&code) => (TrapGroup::Tbl, "tblTrap"),
        _ if (0xA1F6..=0xA233).contains(&code) => (TrapGroup::Win, "winTrap"),
        _ if (0xA800..=0xAFFF).contains(&code) => (TrapGroup::Lib, "libTrapDispatch"),
        _ => (TrapGroup::Unknown, "unknown"),
    };
    TrapMeta { code, group, name }
}
